using Server;
using MazeGeneratorLib;
using MazeLib;
using SearchAlgorithmsLib;
using System;
using System.Collections.Generic;
using System.Net.Sockets;
using System.Linq;

/// <summary>
/// namespace server
/// </summary>
namespace Server
{
    /// <summary>
    /// class Model
    /// </summary>
    /// <seealso cref="Server.IModel" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for Model
    public class Model : IModel
    {
        //members
        /// <summary>
        /// The maze generator
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for mazeGenerator
        private DFSMazeGenerator mazeGenerator;
        /// <summary>
        /// The sol BFS
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for solBFS
        private Solution<Position> solBFS;
        /// <summary>
        /// The sol DFS
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for solDFS
        private Solution<Position> solDFS;
        /// <summary>
        /// The nodes evaluated
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for nodesEvaluated
        private int nodesEvaluated;
        /// <summary>
        /// The maze
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for maze
        private Maze maze;
        /// <summary>
        /// The correct
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for correct
        private Maze correct;
        /// <summary>
        /// The mazes
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for mazes
        private List<Maze> mazes = new List<Maze>();
        /// <summary>
        /// The games
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for games
        private Dictionary<string, Game> games = new Dictionary<string, Game>();
        /// <summary>
        /// The played games
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for playedGames
        private Dictionary<string, Game> playedGames = new Dictionary<string, Game>();
        /// <summary>
        /// The maze exists
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for mazeExists
        private Boolean mazeExists;



        /*
        * GenerateMaze - create the maze
        */
        /// <summary>
        /// Generates the maze.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="rows">The rows.</param>
        /// <param name="cols">The cols.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for GenerateMaze
        public Maze GenerateMaze(string name, int rows, int cols)
        {
            mazeGenerator = new DFSMazeGenerator();
            //this.mazeGenerator = new DFSMazeGenerator();
            maze = mazeGenerator.Generate(rows, cols);
            return maze;
        }

        /// <summary>
        /// Adds the maze,add maze to list of mazes
        /// </summary>
        /// <param name="maze">The maze.</param>
        /// <autogeneratedoc />
        public void AddMaze(Maze maze)
        {
            mazes.Add(maze);
        }


        /// <summary>
        ///  Add game to list of games.
        /// </summary>
        /// <param name="game">The game.</param>
        public void AddGame(Game game)
        {

            games.Add(game.GetName(), game);

        }

        /// <summary>
        /// Prints the maze.
        /// </summary>
        /// <param name="maze">The maze.</param>
        public void PrintMaze(Maze maze)
        {
            System.Console.Write(maze.ToString());
        }

        /*
        * SolveMaze - solve the maze
        */
        /// <summary>
        /// Solves the maze.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="algorithem">The algorithem.</param>
        /// <returns></returns>

        public Solution<Position> SolveMaze(string name, int algorithem)
        {

            //initialize correct maze to null before lookin for maze to solve
            correct = null;

            //find the maze to solve
            foreach (Maze maze in mazes)
            {
                //if a maze with the same name was found - save it
                if (maze.Name == name)
                {
                    correct = maze;
                    mazeExists = true;
                }
            }
            //if maze wasn't found - throw exception
            if (correct == null)
            {
                Console.WriteLine("maze dosn't exist");
                mazeExists = false;
                return null;
            }
            else
            {

                ISearchable<Position> mazeSearch = new MazeSearchableAdaptor(correct);
                //if algorithm no. is 0 - solve maze by BFS
                if (algorithem == 0)
                {
                    BFS<Position> bfs = new BFS<Position>();
                    solBFS = bfs.search(mazeSearch);
                    nodesEvaluated = bfs.getNumberOfNodesEvaluated();
                    return solBFS;
                }
                //if algorithm no. is 1 - solve maze by DFS
                else
                {
                    DFS<Position> dfs = new DFS<Position>();
                    solDFS = dfs.search(mazeSearch);
                    nodesEvaluated = dfs.getNumberOfNodesEvaluated();
                    return solDFS;

                }
            }
        }

        /*
        * GetGameList - get list of games
        */
        /// <summary>
        /// Gets the game list.
        /// </summary>
        /// <returns>
        /// list of games
        /// </returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for GetGameList
        public Dictionary<string, Game> GetGameList()
        {
            return games;
        }

        /*
        * GetMazeList - get list of mazes
        */
        /// <summary>
        /// Doeses the maze exist.
        /// </summary>
        /// <returns>
        /// if maze exists
        /// </returns>
        public bool doesMazeExist()
        {
            return mazeExists;
        }

        /*
        * RemoveGame - remove game from list
        */
        /// <summary>
        /// Removes the game.
        /// </summary>
        /// <param name="removeGame">The remove game.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for RemoveGame
        public void RemoveGame(string removeGame)
        {
            GetGameList().Remove(removeGame);
        }

        /// <summary>
        /// PrintNumStatesBFS - print no. of nodes evaluated by BFS
        /// </summary>
        /// <param name="maze">The maze.</param>
        public void PrintNumStatesBFS(Maze maze)
        {
            Console.WriteLine("Nodes evalueated by BFS: " + nodesEvaluated);
        }


        /// <summary>
        /// PrintNumStatesDFS - print no. of nodes evaluated by DFS
        /// </summary>
        public void PrintNumStatesDFS(Maze maze)
        {
            Console.WriteLine("Nodes evalueated by DFS: " + nodesEvaluated);
        }


        /// <summary>
        ///GetEvaluatedNodes - return no. of nodes evaluated
        /// </summary>
        /// <returns>
        /// no. of evaluated nodes
        /// </returns>

        public int GetEvaluatedNodes()
        {
            return nodesEvaluated;
        }


    }
}